# Generated by Django 5.2.17 on 2026-09-24 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('tireur', models.CharField(max_length=200)),
                ('tire', models.CharField(max_length=200)),
                ('beneficiaire', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('lieu_paiement', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('impayee', 'Impayée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
